name: btserver

services:
  btserver:
    image: cego1200/btserver:latest
    container_name: btserver
    restart: unless-stopped
    environment:
      ENABLE_YTDLP_FETCHER: NO
      # ---
      # YouTube support
      #
      # By enabling this option, you explicitly request the use of the external
      # tool "yt-dlp" to access content from third-party platforms such as YouTube.
      #
      # The use of such platforms is subject to their respective terms of service.
      # You are responsible for ensuring that your usage complies with those terms.

    ports:
      - "38080:38080"
      - "38082:38082"
      - "38083:38083"
      - "5003:5003"
    volumes:
      - ./data/runs:/data/runs
      - ./data/thumb_cache:/data/thumb_cache
      - ./data/ytdlp_cache:/data/ytdlp_cache
      - yt_dlp_bin:/opt/yt-dlp

volumes:
  yt_dlp_bin:
